### ISSUE TITLE
runtime/src/index.ts 里的问题

### ISSUE THREAD

**Issue by NisonChrist** [laper32/rift#16]
1. runtime/src/index.ts 中使用了如 `String`、`Boolean`、`Function` 等非 TypeScript 原始类型，不太理解，是否可以将其替换成 TypeScript 的原始类型，如 `string`、`boolean`、`()=>void` 等。
2. 因为这个 `globalthis` 断言成 `any`，后面就失去了 ts 的类型检查，很不安全，很多类型都无法明确，可能还要确定一下各个函数具体的返回类型等。这块是那啥 deno 的 api 吗 (。
3. 上面做好了之后可以做单测诶，太难了好像。

**Comment by laper32** [comment]
1. String, Boolean, Function它们本身就是TS的原始类型（你可以在dts看到）
2. 对，都是Deno的内置api，和native层导出的api，只能写成any
3. runtime单测不太好做，因为很多都要搭配workspace去搞（aka，一个样例项目）
